[versions]
coreKtxVersion = "1.9.0"
materialVersion = "1.12.0"
activityKtxVersion = "1.9.2"

[libraries]
coreKtx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtxVersion" }
activityKtx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityKtxVersion" }
material = { group = "com.google.android.material", name = "material", version.ref = "materialVersion" }