[versions]
coreKtxVersion = "1.9.0"
materialVersion = "1.8.0"

[libraries]
coreKtx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtxVersion" }
material = { group = "com.google.android.material", name = "material", version.ref = "materialVersion" }