[versions]
coreKtxVersion = "1.16.0"
materialVersion = "1.12.0"
activityKtxVersion = "1.10.1"
splashscreenVersion = "1.0.1"

[libraries]
coreKtx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtxVersion" }
activityKtx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityKtxVersion" }
material = { group = "com.google.android.material", name = "material", version.ref = "materialVersion" }
splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashscreenVersion" }