[versions]
composeVersion = "1.8.2"
activityComposeVersion = "1.10.1"
material3Version = "1.3.2"
lifecycle-viewmodel-compose-version = "2.9.1"
lifecycle-runtime-compose-version = "2.9.1"
navigation-compose-version = "2.9.0"
accompanist-systemuicontroller-version = "0.26.3-beta"
pagingCompose = "3.3.6"

[libraries]
activityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityComposeVersion" }
pagingCompose = { group = "androidx.paging", name = "paging-compose", version.ref = "pagingCompose" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3Version" }
lifecycleViewmodelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel-compose-version" }
lifecycleRuntimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle-runtime-compose-version" }
uiToolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "composeVersion" }
uiTooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "composeVersion" }
navigationCompose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose-version" }
accompanistSystemUicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist-systemuicontroller-version" }
uiTestJunit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "composeVersion" }
uiTestManifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "composeVersion" }

[bundles]
composePreview = ["uiTooling", "uiToolingPreview"]