[versions]
composeVersion = "1.3.3"
activityComposeVersion = "1.6.1"
material3-version = "1.0.1"
lifecycle-viewmodel-compose-version = "2.5.1"
lifecycle-runtime-compose-version = "2.6.0-alpha03"
navigation-compose-version = "2.5.3"
accompanist-systemuicontroller-version = "0.26.3-beta"

[libraries]
activityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityComposeVersion" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3-version" }
lifecycleViewmodelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel-compose-version" }
lifecycleRuntimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle-runtime-compose-version" }
uiToolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "composeVersion" }
uiTooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "composeVersion" }
navigationCompose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose-version" }
accompanistSystemUicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist-systemuicontroller-version" }
uiTestJunit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "composeVersion" }
uiTestManifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "composeVersion" }

[bundles]
composePreview = ["uiTooling", "uiToolingPreview"]