[versions]
bom-version = "32.3.1"

[libraries]
firebaseBOM = { group = "com.google.firebase", name = "firebase-bom", version.ref = "bom-version" }
firebaseCrashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebaseAnalytics = { module = "com.google.firebase:firebase-analytics" }