[versions]
kotlinGradlePluginVersion = "1.9.0"
androidGradlePluginVersion = "8.1.1"
minSdk = "21"
targetSdk = "34"
compileSdk = "34"
kotlinCompilerExtensionVersion = "1.5.1"

[libraries]
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePluginVersion" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlinGradlePluginVersion" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinGradlePluginVersion" }
application = { id = "com.android.application", version.ref = "androidGradlePluginVersion" }
library = { id = "com.android.library", version.ref = "androidGradlePluginVersion" }