[versions]
kotlinGPVersion = "2.0.20"
aGPVersion = "8.7.3" # AGP
kotlinJvmPluginVersion = "1.9.10"
testLoggerVersion = "4.0.0"
minSdk = "21"
targetSdk = "34"
compileSdk = "34"
kotlinCompilerExtensionVersion = "1.5.3"
firebaseCrashlyticsVersion = "3.0.3"

[libraries]
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlinGPVersion" }
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "aGPVersion" }

[plugins]
android-app-gp = { id = "com.android.application", version.ref = "aGPVersion" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinGPVersion" }
android-lib-gp = { id = "com.android.library", version.ref = "aGPVersion" }
kotlin-gp = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinGPVersion" }
kotlin-jvm-gp = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinJvmPluginVersion" }
test-logger = { id = "com.adarshr.test-logger", version.ref = "testLoggerVersion" }
firebase-crashlytics-gp = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsVersion" }

