[versions]
junit = "4.13.2"
androidxTestExt = "1.2.1"
espressoCore = "3.6.1"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidxTestExt = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExt" }
espressoCore = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }