name: Build Simple
on: push
jobs:
  test_job:
    name: Assemble
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Debug Lint
        run: ./gradlew lintDebug

      -name: Run Debug Unit Tests
        run: ./gradlew testDebugUnitTest

        - name: Assemble Debug
          run: ./gradlew assembleDebug